import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { getReview, postGithubComment } from "../api/reviews";
import Navbar from "../components/Navbar";
import ScoreGauge from "../components/ScoreGauge";
import IssueCard from "../components/IssueCard";

const TABS = ["Overview", "Security", "Bugs", "Quality", "Cross-File"];

const LANG_MAP = {
  py: "Python", js: "JavaScript", jsx: "JavaScript", ts: "TypeScript",
  tsx: "TypeScript", java: "Java", go: "Go", rs: "Rust", rb: "Ruby",
  php: "PHP", cpp: "C++", cc: "C++", cxx: "C++", cs: "C#",
};

const LANG_COLORS = {
  Python: "bg-blue-900/60 text-blue-300",
  JavaScript: "bg-yellow-900/60 text-yellow-300",
  TypeScript: "bg-blue-900/60 text-blue-300",
  Java: "bg-orange-900/60 text-orange-300",
  Go: "bg-cyan-900/60 text-cyan-300",
  Rust: "bg-orange-900/60 text-orange-300",
  Ruby: "bg-red-900/60 text-red-300",
  PHP: "bg-purple-900/60 text-purple-300",
  "C++": "bg-pink-900/60 text-pink-300",
  "C#": "bg-purple-900/60 text-purple-300",
};

function detectLanguage(issues) {
  const counts = {};
  for (const issue of issues) {
    if (!issue.file_path) continue;
    const ext = issue.file_path.split(".").pop()?.toLowerCase();
    const lang = LANG_MAP[ext];
    if (lang) counts[lang] = (counts[lang] || 0) + 1;
  }
  const entries = Object.entries(counts);
  if (entries.length === 0) return null;
  return entries.sort((a, b) => b[1] - a[1])[0][0];
}

function exportMarkdown(review) {
  const score = review.overall_score?.toFixed(0) ?? "N/A";
  const lines = [
    `# CodeSentinel Review — ${review.repo_owner}/${review.repo_name} #${review.pr_number}`,
    ``,
    `**PR:** [${review.pr_title || `#${review.pr_number}`}](${review.pr_url})`,
    `**Score:** ${score}/100`,
    `**Status:** ${review.status}`,
    ``,
    `## Summary`,
    ``,
    review.summary || "_No summary available._",
    ``,
  ];

  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };

  function appendIssues(title, issues) {
    if (!issues || issues.length === 0) return;
    lines.push(`## ${title}`, ``);
    const sorted = [...issues].sort(
      (a, b) => (severityOrder[a.severity] ?? 4) - (severityOrder[b.severity] ?? 4)
    );
    for (const issue of sorted) {
      const loc = issue.file_path
        ? `\`${issue.file_path}${issue.line_number ? `:${issue.line_number}` : ""}\``
        : "";
      lines.push(`### [${issue.severity}] ${loc}`);
      lines.push(``, issue.description);
      if (issue.suggestion) lines.push(``, `**Suggestion:** ${issue.suggestion}`);
      lines.push(``);
    }
  }

  const security = review.issues?.filter((i) => i.category === "security") ?? [];
  const bugs = review.issues?.filter((i) => i.category === "bug") ?? [];
  const quality = review.issues?.filter((i) => i.category === "quality") ?? [];
  const crossFile = review.issues?.filter((i) => i.category === "cross_file") ?? [];

  appendIssues("Security Issues", security);
  appendIssues("Bugs", bugs);
  appendIssues("Quality Issues", quality);

  if (crossFile.length > 0) {
    lines.push(`## Cross-File Issues`, ``);
    for (const issue of crossFile) {
      const af = typeof issue.affected_files === "string" ? JSON.parse(issue.affected_files || "[]") : (issue.affected_files ?? []);
      const files = af.join(", ");
      lines.push(`### [${issue.severity}] ${files}`);
      lines.push(``, issue.description);
      if (issue.suggestion) lines.push(``, `**Suggestion:** ${issue.suggestion}`);
      lines.push(``);
    }
  }

  if (review.positive_observations?.length > 0) {
    lines.push(`## Positive Observations`, ``);
    for (const p of review.positive_observations) lines.push(`- ${p}`);
    lines.push(``);
  }

  if (review.top_priorities?.length > 0) {
    lines.push(`## Top Priorities Before Merge`, ``);
    review.top_priorities.forEach((p, i) => lines.push(`${i + 1}. ${p}`));
    lines.push(``);
  }

  lines.push(`---`, `_Generated by CodeSentinel using Claude AI_`);

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${review.repo_name}-${review.pr_number}-review.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function EmptyState({ label }) {
  return (
    <div className="text-center py-16 text-gray-500">
      <p className="text-4xl mb-3">✓</p>
      <p>No {label} found</p>
    </div>
  );
}

export default function ReviewResult() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [review, setReview] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("Overview");
  const [posting, setPosting] = useState(false);
  const [postMsg, setPostMsg] = useState("");

  useEffect(() => {
    (async () => {
      try {
        const { data } = await getReview(id);
        setReview(data);
      } catch {
        navigate("/dashboard");
      } finally {
        setLoading(false);
      }
    })();
  }, [id]);

  async function handlePostComment() {
    setPosting(true);
    setPostMsg("");
    try {
      await postGithubComment(id);
      setPostMsg("Comment posted to GitHub PR!");
    } catch (err) {
      setPostMsg(err.response?.data?.detail || "Failed to post comment");
    } finally {
      setPosting(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center text-gray-400">
        Loading…
      </div>
    );
  }

  if (!review) return null;

  const security = review.issues?.filter((i) => i.category === "security") ?? [];
  const bugs = review.issues?.filter((i) => i.category === "bug") ?? [];
  const quality = review.issues?.filter((i) => i.category === "quality") ?? [];
  const crossFile = review.issues?.filter((i) => i.category === "cross_file") ?? [];

  const tabCounts = {
    Security: security.length,
    Bugs: bugs.length,
    Quality: quality.length,
    "Cross-File": crossFile.length,
  };

  const dominantLang = detectLanguage(review.issues ?? []);
  const langColor = dominantLang ? (LANG_COLORS[dominantLang] || "bg-gray-700 text-gray-300") : null;

  return (
    <div className="min-h-screen bg-gray-950">
      <Navbar />

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-6">
          <button
            onClick={() => navigate("/dashboard")}
            className="text-gray-500 hover:text-gray-300 text-sm mb-3 flex items-center gap-1"
          >
            ← Back to Dashboard
          </button>
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <h1 className="text-xl font-bold text-white">
                  {review.repo_owner}/{review.repo_name}{" "}
                  <span className="text-gray-400 font-normal">#{review.pr_number}</span>
                </h1>
                {dominantLang && (
                  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${langColor}`}>
                    {dominantLang}
                  </span>
                )}
              </div>
              {review.pr_title && (
                <p className="text-gray-400 text-sm mt-1">{review.pr_title}</p>
              )}
              <a
                href={review.pr_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:text-blue-400 text-xs mt-1 inline-block"
              >
                View on GitHub →
              </a>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => exportMarkdown(review)}
                className="bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-300 text-sm px-4 py-2 rounded-lg transition-colors"
              >
                Export .md
              </button>
              <button
                onClick={handlePostComment}
                disabled={posting}
                className="bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-300 text-sm px-4 py-2 rounded-lg transition-colors disabled:opacity-50"
              >
                {posting ? "Posting…" : "Post to GitHub"}
              </button>
            </div>
          </div>
          {postMsg && (
            <p className={`text-sm mt-2 ${postMsg.includes("Failed") ? "text-red-400" : "text-green-400"}`}>
              {postMsg}
            </p>
          )}
        </div>

        {/* Tabs */}
        <div className="flex gap-1 border-b border-gray-800 mb-6">
          {TABS.map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors ${
                activeTab === tab
                  ? "border-blue-500 text-blue-400"
                  : "border-transparent text-gray-500 hover:text-gray-300"
              }`}
            >
              {tab}
              {tabCounts[tab] !== undefined && tabCounts[tab] > 0 && (
                <span className="ml-2 bg-gray-800 text-gray-400 text-xs px-1.5 py-0.5 rounded-full">
                  {tabCounts[tab]}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Tab content */}
        {activeTab === "Overview" && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 flex flex-col items-center">
                <ScoreGauge score={review.overall_score} />
                <div className="mt-4 grid grid-cols-2 gap-4 w-full text-center text-sm">
                  <div>
                    <p className="text-gray-400">Total Issues</p>
                    <p className="text-white font-bold text-lg">{review.total_issues}</p>
                  </div>
                  <div>
                    <p className="text-gray-400">Critical</p>
                    <p className="text-red-400 font-bold text-lg">{review.critical_issues}</p>
                  </div>
                </div>
              </div>

              <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">Summary</h3>
                <p className="text-gray-200 text-sm leading-relaxed">{review.summary}</p>
              </div>
            </div>

            {review.top_priorities?.length > 0 && (
              <div className="bg-gray-900 border border-red-900/50 rounded-xl p-6">
                <h3 className="text-sm font-semibold text-red-400 uppercase tracking-wider mb-3">
                  Top Priorities Before Merge
                </h3>
                <ol className="space-y-2">
                  {review.top_priorities.map((p, i) => (
                    <li key={i} className="flex gap-3 text-sm text-gray-200">
                      <span className="text-red-500 font-bold shrink-0">{i + 1}.</span>
                      {p}
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {review.positive_observations?.length > 0 && (
              <div className="bg-gray-900 border border-green-900/50 rounded-xl p-6">
                <h3 className="text-sm font-semibold text-green-400 uppercase tracking-wider mb-3">
                  Positive Observations
                </h3>
                <ul className="space-y-2">
                  {review.positive_observations.map((p, i) => (
                    <li key={i} className="flex gap-2 text-sm text-gray-200">
                      <span className="text-green-500 shrink-0">✓</span>
                      {p}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {activeTab === "Security" && (
          <div className="space-y-3">
            {security.length === 0 ? (
              <EmptyState label="security issues" />
            ) : (
              security.map((issue) => <IssueCard key={issue.id} issue={issue} />)
            )}
          </div>
        )}

        {activeTab === "Bugs" && (
          <div className="space-y-3">
            {bugs.length === 0 ? (
              <EmptyState label="bugs" />
            ) : (
              bugs.map((issue) => <IssueCard key={issue.id} issue={issue} />)
            )}
          </div>
        )}

        {activeTab === "Quality" && (
          <div className="space-y-3">
            {quality.length === 0 ? (
              <EmptyState label="quality issues" />
            ) : (
              quality.map((issue) => <IssueCard key={issue.id} issue={issue} />)
            )}
          </div>
        )}

        {activeTab === "Cross-File" && (
          <div className="space-y-3">
            {crossFile.length === 0 ? (
              <EmptyState label="cross-file issues" />
            ) : (
              crossFile.map((issue) => <IssueCard key={issue.id} issue={issue} isCrossFile />)
            )}
          </div>
        )}
      </div>
    </div>
  );
}
