import json
import logging
import time
from datetime import datetime, timezone

import redis
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.core.claude_client import ClaudeClient
from app.core.dependency_graph import (
    build_dependency_graph,
    format_dependency_graph,
    parse_diff_files,
)
from app.core.github_client import GitHubClient
from app.core.score_calculator import calculate_score, count_issues
from app.database import AsyncSessionLocal
from app.models.review import Review
from app.models.review_issue import ReviewIssue

settings = get_settings()
logger = logging.getLogger(__name__)

_CHARS_PER_TOKEN = 4
_MAX_CHARS = settings.MAX_DIFF_TOKENS * _CHARS_PER_TOKEN


def _truncate_diff(diff: str, max_files: int, max_chars: int) -> tuple[str, list[str], int]:
    """
    Split diff by file, keep up to max_files, truncate total length to max_chars.
    Returns (truncated_diff, file_list, approx_token_count).
    """
    sections: list[tuple[str, str]] = []
    current_header = ""
    current_lines: list[str] = []

    for line in diff.splitlines(keepends=True):
        if line.startswith("diff --git"):
            if current_header:
                sections.append((current_header, "".join(current_lines)))
            current_header = line
            current_lines = []
        else:
            current_lines.append(line)

    if current_header:
        sections.append((current_header, "".join(current_lines)))

    selected = sections[:max_files]
    combined = "".join(h + b for h, b in selected)
    truncated = combined[:max_chars]
    file_list = parse_diff_files(truncated)
    token_count = len(truncated) // _CHARS_PER_TOKEN
    return truncated, file_list, token_count


def _build_github_comment(review_data: dict, score: float, pr_url: str) -> str:
    lines = [
        f"## CodeSentinel Review — Score: {score:.0f}/100\n",
        f"**Summary:** {review_data.get('summary', '')}\n",
    ]

    for category, label in [
        ("security_issues", "Security Issues"),
        ("bugs", "Bugs"),
        ("quality_issues", "Quality Issues"),
    ]:
        issues = review_data.get(category, [])
        if issues:
            lines.append(f"\n### {label}\n")
            for i in issues:
                lines.append(
                    f"- **[{i['severity']}]** `{i.get('file', 'unknown')}:{i.get('line', '?')}` — {i['description']}"
                )

    cross = review_data.get("cross_file_issues", [])
    if cross:
        lines.append("\n### Cross-File Issues\n")
        for i in cross:
            files = ", ".join(i.get("affected_files", []))
            lines.append(f"- **[{files}]** {i['description']}")

    positives = review_data.get("positive_observations", [])
    if positives:
        lines.append("\n### Positive Observations\n")
        for p in positives:
            lines.append(f"- {p}")

    priorities = review_data.get("top_priorities", [])
    if priorities:
        lines.append("\n### Top Priorities Before Merge\n")
        for idx, p in enumerate(priorities, 1):
            lines.append(f"{idx}. {p}")

    lines.append(f"\n---\n*Generated by [CodeSentinel]({pr_url}) using Claude AI*")
    return "\n".join(lines)


class ReviewPipeline:
    def __init__(self, review_id: int, github_token: str | None = None):
        self.review_id = review_id
        self.github = GitHubClient(token=github_token)
        self.claude = ClaudeClient()
        self._redis = redis.Redis.from_url(settings.REDIS_URL, decode_responses=True)

    def _publish(self, step: str, message: str, progress: int, status: str = "processing"):
        event = json.dumps(
            {"step": step, "message": message, "progress": progress, "status": status}
        )
        self._redis.publish(f"review:{self.review_id}:progress", event)

    def _log_stage(self, stage: str, duration_ms: float, **extra):
        logger.info(
            "pipeline_stage",
            extra={
                "review_id": self.review_id,
                "stage": stage,
                "duration_ms": round(duration_ms, 1),
                "model": "mock" if settings.AI_MOCK else settings.CLAUDE_MODEL,
                **extra,
            },
        )

    async def run(self, pr_url: str, owner: str, repo: str, pr_number: int):
        pipeline_start = time.monotonic()
        async with AsyncSessionLocal() as db:
            await self._update_status(db, "processing")

        try:
            # Step 1 — fetch PR metadata
            self._publish("fetching_pr", "Fetching PR information from GitHub…", 10)
            t = time.monotonic()
            pr_info = await self.github.get_pr_info(owner, repo, pr_number)
            pr_title = pr_info.get("title", f"PR #{pr_number}")
            self._log_stage("fetching_pr", (time.monotonic() - t) * 1000)

            # Check Redis cache — same PR URL never reviewed twice
            cache_key = f"review_cache:{pr_url}"
            cached = self._redis.get(cache_key)
            if cached:
                self._publish("cache_hit", "Loaded from cache — skipping AI call.", 80)
                review_data = json.loads(cached)
                self._log_stage("cache_hit", 0, cache=True)
            else:
                # Step 2 — fetch diff
                self._publish("fetching_diff", "Fetching PR diff…", 25)
                t = time.monotonic()
                raw_diff = await self.github.get_pr_diff(owner, repo, pr_number)
                self._log_stage("fetching_diff", (time.monotonic() - t) * 1000)

                # Step 3 — dependency graph
                self._publish("building_graph", "Building file dependency graph…", 38)
                t = time.monotonic()
                dep_graph = build_dependency_graph(raw_diff)
                dep_summary = format_dependency_graph(dep_graph)
                self._log_stage("building_graph", (time.monotonic() - t) * 1000)

                # Step 4 — truncate
                self._publish("truncating", "Preparing context for AI…", 48)
                t = time.monotonic()
                diff, file_list, token_count = _truncate_diff(
                    raw_diff, settings.MAX_FILES_PER_REVIEW, _MAX_CHARS
                )
                self._log_stage("truncating", (time.monotonic() - t) * 1000, token_count=token_count)

                # Step 5 — AI review
                self._publish("reviewing", "Analyzing code with Claude AI…", 60)
                t = time.monotonic()
                review_data = await self.claude.review_pr(
                    diff=diff,
                    pr_title=pr_title,
                    owner=owner,
                    repo=repo,
                    file_list=file_list,
                    dependency_graph=dep_summary,
                    token_count=token_count,
                )
                self._log_stage("ai_review", (time.monotonic() - t) * 1000)

                # Cache result
                self._redis.setex(cache_key, settings.REDIS_CACHE_TTL, json.dumps(review_data))

            # Step 6 — score
            self._publish("scoring", "Calculating review score…", 78)
            t = time.monotonic()
            score = calculate_score(review_data)
            total_issues, critical_issues = count_issues(review_data)
            self._log_stage("scoring", (time.monotonic() - t) * 1000, score=score, total_issues=total_issues)

            # Step 7 — save to DB
            self._publish("saving", "Saving results to database…", 90)
            t = time.monotonic()
            async with AsyncSessionLocal() as db:
                await self._save_results(
                    db, pr_title, review_data, score, total_issues, critical_issues
                )
            self._log_stage("saving", (time.monotonic() - t) * 1000)

            total_ms = (time.monotonic() - pipeline_start) * 1000
            logger.info(
                "pipeline_complete",
                extra={
                    "review_id": self.review_id,
                    "total_duration_ms": round(total_ms, 1),
                    "score": score,
                    "total_issues": total_issues,
                    "model": "mock" if settings.AI_MOCK else settings.CLAUDE_MODEL,
                },
            )
            self._publish("completed", "Review complete!", 100, status="completed")

        except Exception as exc:
            total_ms = (time.monotonic() - pipeline_start) * 1000
            logger.exception(
                "pipeline_failed",
                extra={
                    "review_id": self.review_id,
                    "total_duration_ms": round(total_ms, 1),
                    "error_type": type(exc).__name__,
                    "model": "mock" if settings.AI_MOCK else settings.CLAUDE_MODEL,
                },
            )
            async with AsyncSessionLocal() as db:
                await self._update_status(db, "failed", str(exc))
            self._publish("failed", f"Review failed: {exc}", 0, status="failed")
            raise

    async def _update_status(self, db: AsyncSession, status: str, error: str | None = None):
        result = await db.execute(select(Review).where(Review.id == self.review_id))
        review = result.scalar_one()
        review.status = status
        if error:
            review.error_message = error
        await db.commit()

    async def _save_results(
        self,
        db: AsyncSession,
        pr_title: str,
        review_data: dict,
        score: float,
        total_issues: int,
        critical_issues: int,
    ):
        result = await db.execute(select(Review).where(Review.id == self.review_id))
        review = result.scalar_one()

        review.pr_title = pr_title
        review.overall_score = score
        review.summary = review_data.get("summary")
        review.status = "completed"
        review.total_issues = total_issues
        review.critical_issues = critical_issues
        review.positive_observations = review_data.get("positive_observations", [])
        review.top_priorities = review_data.get("top_priorities", [])
        review.completed_at = datetime.now(timezone.utc)

        for category, field in [
            ("security_issues", "security"),
            ("bugs", "bug"),
            ("quality_issues", "quality"),
        ]:
            for issue in review_data.get(category, []):
                db.add(
                    ReviewIssue(
                        review_id=self.review_id,
                        category=field,
                        severity=issue.get("severity", "MEDIUM"),
                        file_path=issue.get("file"),
                        line_number=issue.get("line"),
                        description=issue.get("description", ""),
                        suggestion=issue.get("suggestion"),
                    )
                )

        for issue in review_data.get("cross_file_issues", []):
            db.add(
                ReviewIssue(
                    review_id=self.review_id,
                    category="cross_file",
                    severity=issue.get("severity", "MEDIUM"),
                    description=issue.get("description", ""),
                    suggestion=issue.get("suggestion"),
                    affected_files=json.dumps(issue.get("affected_files", [])),
                )
            )

        await db.commit()
